package com.doris.sample.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.trt.servicedownload.module.entity.DownloadFile;
import com.example.trt.servicedownload.module.entity.UpdateFile;

import com.doris.sample.greendao.DownloadFileDao;
import com.doris.sample.greendao.UpdateFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadFileDaoConfig;
    private final DaoConfig updateFileDaoConfig;

    private final DownloadFileDao downloadFileDao;
    private final UpdateFileDao updateFileDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadFileDaoConfig = daoConfigMap.get(DownloadFileDao.class).clone();
        downloadFileDaoConfig.initIdentityScope(type);

        updateFileDaoConfig = daoConfigMap.get(UpdateFileDao.class).clone();
        updateFileDaoConfig.initIdentityScope(type);

        downloadFileDao = new DownloadFileDao(downloadFileDaoConfig, this);
        updateFileDao = new UpdateFileDao(updateFileDaoConfig, this);

        registerDao(DownloadFile.class, downloadFileDao);
        registerDao(UpdateFile.class, updateFileDao);
    }
    
    public void clear() {
        downloadFileDaoConfig.clearIdentityScope();
        updateFileDaoConfig.clearIdentityScope();
    }

    public DownloadFileDao getDownloadFileDao() {
        return downloadFileDao;
    }

    public UpdateFileDao getUpdateFileDao() {
        return updateFileDao;
    }

}
